### ISSUE TITLE
Production status?

### ISSUE THREAD

**Issue by tomtom215** [StarRocks/dbt-starrocks#14]
Hello all,

As we are investigating Starrocks for production, integration with DBT is critical for us.

I have seen from the other issues and comments that this adapter is still in early phases and will be added to DBT's official adapter documentation but I wanted to inquire if there was any roadmap or rough timeline that can be shared?

Thank you!

**Comment by motto1314** [comment]
Hi, Iterations will be transferred to:
```
https://github.com/StarRocks/starrocks/tree/main/contrib/dbt-connector
```

and use StarRocks-2.4+ please.

In fact, it is now available, you can try it and develop together.
